SET FOREIGN_KEY_CHECKS=0;
INSERT INTO `kategori` (`nama`) SELECT 'Acrylic' WHERE NOT EXISTS (SELECT 1 FROM `kategori` WHERE `nama` = 'Acrylic');
INSERT INTO `kategori` (`nama`) SELECT 'Alkyd' WHERE NOT EXISTS (SELECT 1 FROM `kategori` WHERE `nama` = 'Alkyd');
INSERT INTO `kategori` (`nama`) SELECT 'Anti Fouling' WHERE NOT EXISTS (SELECT 1 FROM `kategori` WHERE `nama` = 'Anti Fouling');
INSERT INTO `kategori` (`nama`) SELECT 'Decorative' WHERE NOT EXISTS (SELECT 1 FROM `kategori` WHERE `nama` = 'Decorative');
INSERT INTO `kategori` (`nama`) SELECT 'Epoxy' WHERE NOT EXISTS (SELECT 1 FROM `kategori` WHERE `nama` = 'Epoxy');
INSERT INTO `kategori` (`nama`) SELECT 'Floor' WHERE NOT EXISTS (SELECT 1 FROM `kategori` WHERE `nama` = 'Floor');
INSERT INTO `kategori` (`nama`) SELECT 'Heat Resistance' WHERE NOT EXISTS (SELECT 1 FROM `kategori` WHERE `nama` = 'Heat Resistance');
INSERT INTO `kategori` (`nama`) SELECT 'Polyurethane' WHERE NOT EXISTS (SELECT 1 FROM `kategori` WHERE `nama` = 'Polyurethane');
INSERT INTO `kategori` (`nama`) SELECT 'Waterproofing' WHERE NOT EXISTS (SELECT 1 FROM `kategori` WHERE `nama` = 'Waterproofing');
INSERT INTO `kategori` (`nama`) SELECT 'Zinc Rich' WHERE NOT EXISTS (SELECT 1 FROM `kategori` WHERE `nama` = 'Zinc Rich');
INSERT IGNORE INTO `sub_kategori` (`nama`) VALUES ('Finish 3rd');
INSERT IGNORE INTO `sub_kategori` (`nama`) VALUES ('Finish Gloss 2nd');
INSERT IGNORE INTO `sub_kategori` (`nama`) VALUES ('Finish Gloss 3rd');
INSERT IGNORE INTO `sub_kategori` (`nama`) VALUES ('Finish Matte 3rd');
INSERT IGNORE INTO `sub_kategori` (`nama`) VALUES ('Mortar');
INSERT IGNORE INTO `sub_kategori` (`nama`) VALUES ('Primer 1st');
INSERT IGNORE INTO `sub_kategori` (`nama`) VALUES ('Primer 2nd');
INSERT IGNORE INTO `sub_kategori` (`nama`) VALUES ('Protect 1st');
INSERT IGNORE INTO `sub_kategori` (`nama`) VALUES ('Protect 2nd');
INSERT IGNORE INTO `sub_kategori` (`nama`) VALUES ('Protect 3rd');
INSERT IGNORE INTO `lokasi_penggunaan` (`nama`) VALUES ('Besi');
INSERT IGNORE INTO `lokasi_penggunaan` (`nama`) VALUES ('Besi Indoor');
INSERT IGNORE INTO `lokasi_penggunaan` (`nama`) VALUES ('Besi Outdoor');
INSERT IGNORE INTO `lokasi_penggunaan` (`nama`) VALUES ('Beton Basah');
INSERT IGNORE INTO `lokasi_penggunaan` (`nama`) VALUES ('Beton Indoor');
INSERT IGNORE INTO `lokasi_penggunaan` (`nama`) VALUES ('Beton Outdoor');
INSERT IGNORE INTO `lokasi_penggunaan` (`nama`) VALUES ('Dalam Air');
INSERT IGNORE INTO `lokasi_penggunaan` (`nama`) VALUES ('Kayu');
INSERT IGNORE INTO `lokasi_penggunaan` (`nama`) VALUES ('Lantai Basah');
INSERT IGNORE INTO `lokasi_penggunaan` (`nama`) VALUES ('Lantai Kering');
INSERT IGNORE INTO `lokasi_penggunaan` (`nama`) VALUES ('Room Exterior');
INSERT IGNORE INTO `lokasi_penggunaan` (`nama`) VALUES ('Room Interior');
INSERT IGNORE INTO `kebutuhan` (`nama`) VALUES ('Anti Karat');
INSERT IGNORE INTO `kebutuhan` (`nama`) VALUES ('Anti Static');
INSERT IGNORE INTO `kebutuhan` (`nama`) VALUES ('Bawah Kapal');
INSERT IGNORE INTO `kebutuhan` (`nama`) VALUES ('Bersinar Saat Gelap');
INSERT IGNORE INTO `kebutuhan` (`nama`) VALUES ('Cepat Kering');
INSERT IGNORE INTO `kebutuhan` (`nama`) VALUES ('Elastis');
INSERT IGNORE INTO `kebutuhan` (`nama`) VALUES ('Marka');
INSERT IGNORE INTO `kebutuhan` (`nama`) VALUES ('Mudah Dibersihkan');
INSERT IGNORE INTO `kebutuhan` (`nama`) VALUES ('Oily Surfaces');
INSERT IGNORE INTO `kebutuhan` (`nama`) VALUES ('Tahan Abrasi');
INSERT IGNORE INTO `kebutuhan` (`nama`) VALUES ('Tahan Bahan Bakar');
INSERT IGNORE INTO `kebutuhan` (`nama`) VALUES ('Tahan Benturan');
INSERT IGNORE INTO `kebutuhan` (`nama`) VALUES ('Tahan Cuaca');
INSERT IGNORE INTO `kebutuhan` (`nama`) VALUES ('Tahan Gesekan');
INSERT IGNORE INTO `kebutuhan` (`nama`) VALUES ('Tahan Karat');
INSERT IGNORE INTO `kebutuhan` (`nama`) VALUES ('Tahan Kimia');
INSERT IGNORE INTO `kebutuhan` (`nama`) VALUES ('Tahan Panas');
INSERT IGNORE INTO `kebutuhan` (`nama`) VALUES ('Tahan Sinar Matahari');
INSERT IGNORE INTO `kebutuhan` (`nama`) VALUES ('Tidak Bau Tajam');
INSERT IGNORE INTO `kebutuhan` (`nama`) VALUES ('Viskositas Rendah');

DELETE FROM `hasil_rekomendasi`;
DELETE FROM `produk_kebutuhan`;
DELETE FROM `produk_lokasi_penggunaan`;
DELETE FROM `produk_sub_kategori`;
DELETE FROM `produk`;
ALTER TABLE `produk` AUTO_INCREMENT = 1;

INSERT INTO `produk` (`id_produk`, `nama`, `id_kategori`) VALUES
(1, 'FOXACRYL ENAMEL', (SELECT `id_kategori` FROM `kategori` WHERE `nama` = 'Acrylic' LIMIT 1)),
(2, 'FOXACRYL PRIMER', (SELECT `id_kategori` FROM `kategori` WHERE `nama` = 'Acrylic' LIMIT 1)),
(3, 'FOXANYL ESTER GF', (SELECT `id_kategori` FROM `kategori` WHERE `nama` = 'Acrylic' LIMIT 1)),
(4, 'FOXANYL ESTER', (SELECT `id_kategori` FROM `kategori` WHERE `nama` = 'Acrylic' LIMIT 1)),
(5, 'FOXAGLOW', (SELECT `id_kategori` FROM `kategori` WHERE `nama` = 'Acrylic' LIMIT 1)),
(6, 'FOXACRYL-FP', (SELECT `id_kategori` FROM `kategori` WHERE `nama` = 'Acrylic' LIMIT 1)),
(7, 'FOXABITUMEN - VARNISH', (SELECT `id_kategori` FROM `kategori` WHERE `nama` = 'Acrylic' LIMIT 1)),
(8, 'FOXAKYD-ZP', (SELECT `id_kategori` FROM `kategori` WHERE `nama` = 'Alkyd' LIMIT 1)),
(9, 'FOXAKYD-ZC', (SELECT `id_kategori` FROM `kategori` WHERE `nama` = 'Alkyd' LIMIT 1)),
(10, 'FOXAKYD ENAMEL', (SELECT `id_kategori` FROM `kategori` WHERE `nama` = 'Alkyd' LIMIT 1)),
(11, 'FOXAKYD-QD', (SELECT `id_kategori` FROM `kategori` WHERE `nama` = 'Alkyd' LIMIT 1)),
(12, 'FOXA-NC', (SELECT `id_kategori` FROM `kategori` WHERE `nama` = 'Alkyd' LIMIT 1)),
(13, 'FOXABITUMEN - VARNISH', (SELECT `id_kategori` FROM `kategori` WHERE `nama` = 'Alkyd' LIMIT 1)),
(14, 'FOXARUST', (SELECT `id_kategori` FROM `kategori` WHERE `nama` = 'Alkyd' LIMIT 1)),
(15, 'FOXAPOX-HB', (SELECT `id_kategori` FROM `kategori` WHERE `nama` = 'Epoxy' LIMIT 1)),
(16, 'FOXAPOX-TC', (SELECT `id_kategori` FROM `kategori` WHERE `nama` = 'Epoxy' LIMIT 1)),
(17, 'FOXAPOX ETCH', (SELECT `id_kategori` FROM `kategori` WHERE `nama` = 'Epoxy' LIMIT 1)),
(18, 'FOXAPOX-ZP', (SELECT `id_kategori` FROM `kategori` WHERE `nama` = 'Epoxy' LIMIT 1)),
(19, 'FOXATAR', (SELECT `id_kategori` FROM `kategori` WHERE `nama` = 'Epoxy' LIMIT 1)),
(20, 'FOXAPOX LINING', (SELECT `id_kategori` FROM `kategori` WHERE `nama` = 'Epoxy' LIMIT 1)),
(21, 'FOXAPOX-GF', (SELECT `id_kategori` FROM `kategori` WHERE `nama` = 'Epoxy' LIMIT 1)),
(22, 'FOXAPOX-MULTI', (SELECT `id_kategori` FROM `kategori` WHERE `nama` = 'Epoxy' LIMIT 1)),
(23, 'FOXAPOX-PHENOLIC', (SELECT `id_kategori` FROM `kategori` WHERE `nama` = 'Epoxy' LIMIT 1)),
(24, 'FOXAPOX WEAR MIC', (SELECT `id_kategori` FROM `kategori` WHERE `nama` = 'Epoxy' LIMIT 1)),
(25, 'FOXAPOX-PRIME', (SELECT `id_kategori` FROM `kategori` WHERE `nama` = 'Epoxy' LIMIT 1)),
(26, 'FOXAPOX-DS', (SELECT `id_kategori` FROM `kategori` WHERE `nama` = 'Epoxy' LIMIT 1)),
(27, 'FOXAPOX-UW', (SELECT `id_kategori` FROM `kategori` WHERE `nama` = 'Epoxy' LIMIT 1)),
(28, 'FOXAPOX', (SELECT `id_kategori` FROM `kategori` WHERE `nama` = 'Epoxy' LIMIT 1)),
(29, 'FOXAPOX-CR', (SELECT `id_kategori` FROM `kategori` WHERE `nama` = 'Epoxy' LIMIT 1)),
(30, 'FOXATHANE-GL GLOSS', (SELECT `id_kategori` FROM `kategori` WHERE `nama` = 'Polyurethane' LIMIT 1)),
(31, 'FOXATHANE-GL MATTE', (SELECT `id_kategori` FROM `kategori` WHERE `nama` = 'Polyurethane' LIMIT 1)),
(32, 'FOXATHANE', (SELECT `id_kategori` FROM `kategori` WHERE `nama` = 'Polyurethane' LIMIT 1)),
(33, 'FOXATHANE NEW', (SELECT `id_kategori` FROM `kategori` WHERE `nama` = 'Polyurethane' LIMIT 1)),
(34, 'FOXATIC', (SELECT `id_kategori` FROM `kategori` WHERE `nama` = 'Polyurethane' LIMIT 1)),
(35, 'FOXATHANE-NS', (SELECT `id_kategori` FROM `kategori` WHERE `nama` = 'Polyurethane' LIMIT 1)),
(36, 'FOXATHANE PU 2K', (SELECT `id_kategori` FROM `kategori` WHERE `nama` = 'Polyurethane' LIMIT 1)),
(37, 'FOXATHANE CLEAR', (SELECT `id_kategori` FROM `kategori` WHERE `nama` = 'Polyurethane' LIMIT 1)),
(38, 'FOXAZINC-EP GLOSS', (SELECT `id_kategori` FROM `kategori` WHERE `nama` = 'Polyurethane' LIMIT 1)),
(39, 'FOXAZINC-EP MATTE', (SELECT `id_kategori` FROM `kategori` WHERE `nama` = 'Polyurethane' LIMIT 1)),
(40, 'FOXAZINC-EP', (SELECT `id_kategori` FROM `kategori` WHERE `nama` = 'Zinc Rich' LIMIT 1)),
(41, 'FOXAZINC-FT', (SELECT `id_kategori` FROM `kategori` WHERE `nama` = 'Zinc Rich' LIMIT 1)),
(42, 'FOXAZINC-SP', (SELECT `id_kategori` FROM `kategori` WHERE `nama` = 'Zinc Rich' LIMIT 1)),
(43, 'FOXAZINC-AL', (SELECT `id_kategori` FROM `kategori` WHERE `nama` = 'Zinc Rich' LIMIT 1)),
(44, 'FOXAPRO 200', (SELECT `id_kategori` FROM `kategori` WHERE `nama` = 'Heat Resistance' LIMIT 1)),
(45, 'FOXAPRO 400', (SELECT `id_kategori` FROM `kategori` WHERE `nama` = 'Heat Resistance' LIMIT 1)),
(46, 'FOXAMINE', (SELECT `id_kategori` FROM `kategori` WHERE `nama` = 'Heat Resistance' LIMIT 1)),
(47, 'FOXAFLOOR PRIMER', (SELECT `id_kategori` FROM `kategori` WHERE `nama` = 'Floor' LIMIT 1)),
(48, 'FOXAFLOOR-WB', (SELECT `id_kategori` FROM `kategori` WHERE `nama` = 'Floor' LIMIT 1)),
(49, 'FOXAFLOOR-ESD', (SELECT `id_kategori` FROM `kategori` WHERE `nama` = 'Floor' LIMIT 1)),
(50, 'FOXACEM ECC-85', (SELECT `id_kategori` FROM `kategori` WHERE `nama` = 'Floor' LIMIT 1)),
(51, 'FOXAFLOOR CLEAR', (SELECT `id_kategori` FROM `kategori` WHERE `nama` = 'Floor' LIMIT 1)),
(52, 'FOXAFLOOR CLEAR NEW', (SELECT `id_kategori` FROM `kategori` WHERE `nama` = 'Floor' LIMIT 1)),
(53, 'FOXAFLOOR CLEAR SL', (SELECT `id_kategori` FROM `kategori` WHERE `nama` = 'Floor' LIMIT 1)),
(54, 'FOXA SEALER WB FLOOR', (SELECT `id_kategori` FROM `kategori` WHERE `nama` = 'Floor' LIMIT 1)),
(55, 'FOXABOND SBR', (SELECT `id_kategori` FROM `kategori` WHERE `nama` = 'Floor' LIMIT 1)),
(56, 'FOXAFLOOR-TC', (SELECT `id_kategori` FROM `kategori` WHERE `nama` = 'Floor' LIMIT 1)),
(57, 'FOXAFLOOR-SLW', (SELECT `id_kategori` FROM `kategori` WHERE `nama` = 'Floor' LIMIT 1)),
(58, 'FOXAFLOOR-SLW NEW', (SELECT `id_kategori` FROM `kategori` WHERE `nama` = 'Floor' LIMIT 1)),
(59, 'FOXAFLOOR CLEAR', (SELECT `id_kategori` FROM `kategori` WHERE `nama` = 'Floor' LIMIT 1)),
(60, 'FOXAFLOOR-ESD', (SELECT `id_kategori` FROM `kategori` WHERE `nama` = 'Floor' LIMIT 1)),
(61, 'FOXAPLAST', (SELECT `id_kategori` FROM `kategori` WHERE `nama` = 'Floor' LIMIT 1)),
(62, 'FOXAFLOOR-NO SKID', (SELECT `id_kategori` FROM `kategori` WHERE `nama` = 'Floor' LIMIT 1)),
(63, 'FOXACOTE 3000', (SELECT `id_kategori` FROM `kategori` WHERE `nama` = 'Floor' LIMIT 1)),
(64, 'FOXASEALER WB', (SELECT `id_kategori` FROM `kategori` WHERE `nama` = 'Decorative' LIMIT 1)),
(65, 'FOXAFILLER', (SELECT `id_kategori` FROM `kategori` WHERE `nama` = 'Decorative' LIMIT 1)),
(66, 'FOXAPLAST', (SELECT `id_kategori` FROM `kategori` WHERE `nama` = 'Decorative' LIMIT 1)),
(67, 'FOXAGARD', (SELECT `id_kategori` FROM `kategori` WHERE `nama` = 'Decorative' LIMIT 1)),
(68, 'FOXASHIELD', (SELECT `id_kategori` FROM `kategori` WHERE `nama` = 'Decorative' LIMIT 1)),
(69, 'FOXAFLEX', (SELECT `id_kategori` FROM `kategori` WHERE `nama` = 'Decorative' LIMIT 1)),
(70, 'FOXAPROOF', (SELECT `id_kategori` FROM `kategori` WHERE `nama` = 'Decorative' LIMIT 1)),
(71, 'FOXAPROOF', (SELECT `id_kategori` FROM `kategori` WHERE `nama` = 'Waterproofing' LIMIT 1)),
(72, 'FOXASEAL', (SELECT `id_kategori` FROM `kategori` WHERE `nama` = 'Waterproofing' LIMIT 1)),
(73, 'FOXALASTIC', (SELECT `id_kategori` FROM `kategori` WHERE `nama` = 'Waterproofing' LIMIT 1)),
(74, 'FOXABOND SBR', (SELECT `id_kategori` FROM `kategori` WHERE `nama` = 'Waterproofing' LIMIT 1)),
(75, 'FOXATHANE', (SELECT `id_kategori` FROM `kategori` WHERE `nama` = 'Waterproofing' LIMIT 1)),
(76, 'FOXATIC', (SELECT `id_kategori` FROM `kategori` WHERE `nama` = 'Waterproofing' LIMIT 1)),
(77, 'FOXALING-TR', (SELECT `id_kategori` FROM `kategori` WHERE `nama` = 'Anti Fouling' LIMIT 1)),
(78, 'FOXALING-SP', (SELECT `id_kategori` FROM `kategori` WHERE `nama` = 'Anti Fouling' LIMIT 1));

INSERT INTO `produk_sub_kategori` (`id_produk`, `id_sub_kategori`) VALUES
(1, (SELECT `id_sub_kategori` FROM `sub_kategori` WHERE `nama` = 'Finish Gloss 3rd' LIMIT 1)),
(2, (SELECT `id_sub_kategori` FROM `sub_kategori` WHERE `nama` = 'Primer 1st' LIMIT 1)),
(2, (SELECT `id_sub_kategori` FROM `sub_kategori` WHERE `nama` = 'Primer 2nd' LIMIT 1)),
(3, (SELECT `id_sub_kategori` FROM `sub_kategori` WHERE `nama` = 'Finish Matte 3rd' LIMIT 1)),
(4, (SELECT `id_sub_kategori` FROM `sub_kategori` WHERE `nama` = 'Finish 3rd' LIMIT 1)),
(5, (SELECT `id_sub_kategori` FROM `sub_kategori` WHERE `nama` = 'Finish 3rd' LIMIT 1)),
(6, (SELECT `id_sub_kategori` FROM `sub_kategori` WHERE `nama` = 'Protect 3rd' LIMIT 1)),
(7, (SELECT `id_sub_kategori` FROM `sub_kategori` WHERE `nama` = 'Protect 3rd' LIMIT 1)),
(8, (SELECT `id_sub_kategori` FROM `sub_kategori` WHERE `nama` = 'Primer 1st' LIMIT 1)),
(8, (SELECT `id_sub_kategori` FROM `sub_kategori` WHERE `nama` = 'Primer 2nd' LIMIT 1)),
(9, (SELECT `id_sub_kategori` FROM `sub_kategori` WHERE `nama` = 'Primer 1st' LIMIT 1)),
(10, (SELECT `id_sub_kategori` FROM `sub_kategori` WHERE `nama` = 'Finish 3rd' LIMIT 1)),
(11, (SELECT `id_sub_kategori` FROM `sub_kategori` WHERE `nama` = 'Finish 3rd' LIMIT 1)),
(12, (SELECT `id_sub_kategori` FROM `sub_kategori` WHERE `nama` = 'Finish Gloss 3rd' LIMIT 1)),
(13, (SELECT `id_sub_kategori` FROM `sub_kategori` WHERE `nama` = 'Protect 3rd' LIMIT 1)),
(14, (SELECT `id_sub_kategori` FROM `sub_kategori` WHERE `nama` = 'Protect 3rd' LIMIT 1)),
(15, (SELECT `id_sub_kategori` FROM `sub_kategori` WHERE `nama` = 'Primer 1st' LIMIT 1)),
(15, (SELECT `id_sub_kategori` FROM `sub_kategori` WHERE `nama` = 'Primer 2nd' LIMIT 1)),
(16, (SELECT `id_sub_kategori` FROM `sub_kategori` WHERE `nama` = 'Finish Gloss 3rd' LIMIT 1)),
(17, (SELECT `id_sub_kategori` FROM `sub_kategori` WHERE `nama` = 'Primer 1st' LIMIT 1)),
(17, (SELECT `id_sub_kategori` FROM `sub_kategori` WHERE `nama` = 'Primer 2nd' LIMIT 1)),
(18, (SELECT `id_sub_kategori` FROM `sub_kategori` WHERE `nama` = 'Primer 1st' LIMIT 1)),
(18, (SELECT `id_sub_kategori` FROM `sub_kategori` WHERE `nama` = 'Primer 2nd' LIMIT 1)),
(19, (SELECT `id_sub_kategori` FROM `sub_kategori` WHERE `nama` = 'Protect 3rd' LIMIT 1)),
(20, (SELECT `id_sub_kategori` FROM `sub_kategori` WHERE `nama` = 'Protect 3rd' LIMIT 1)),
(21, (SELECT `id_sub_kategori` FROM `sub_kategori` WHERE `nama` = 'Finish 3rd' LIMIT 1)),
(22, (SELECT `id_sub_kategori` FROM `sub_kategori` WHERE `nama` = 'Finish 3rd' LIMIT 1)),
(23, (SELECT `id_sub_kategori` FROM `sub_kategori` WHERE `nama` = 'Protect 3rd' LIMIT 1)),
(24, (SELECT `id_sub_kategori` FROM `sub_kategori` WHERE `nama` = 'Protect 3rd' LIMIT 1)),
(25, (SELECT `id_sub_kategori` FROM `sub_kategori` WHERE `nama` = 'Finish 3rd' LIMIT 1)),
(26, (SELECT `id_sub_kategori` FROM `sub_kategori` WHERE `nama` = 'Finish 3rd' LIMIT 1)),
(27, (SELECT `id_sub_kategori` FROM `sub_kategori` WHERE `nama` = 'Finish Gloss 2nd' LIMIT 1)),
(27, (SELECT `id_sub_kategori` FROM `sub_kategori` WHERE `nama` = 'Finish Gloss 3rd' LIMIT 1)),
(28, (SELECT `id_sub_kategori` FROM `sub_kategori` WHERE `nama` = 'Mortar' LIMIT 1)),
(29, (SELECT `id_sub_kategori` FROM `sub_kategori` WHERE `nama` = 'Finish 3rd' LIMIT 1)),
(30, (SELECT `id_sub_kategori` FROM `sub_kategori` WHERE `nama` = 'Finish Gloss 3rd' LIMIT 1)),
(31, (SELECT `id_sub_kategori` FROM `sub_kategori` WHERE `nama` = 'Finish Matte 3rd' LIMIT 1)),
(32, (SELECT `id_sub_kategori` FROM `sub_kategori` WHERE `nama` = 'Finish 3rd' LIMIT 1)),
(33, (SELECT `id_sub_kategori` FROM `sub_kategori` WHERE `nama` = 'Finish 3rd' LIMIT 1)),
(34, (SELECT `id_sub_kategori` FROM `sub_kategori` WHERE `nama` = 'Finish 3rd' LIMIT 1)),
(35, (SELECT `id_sub_kategori` FROM `sub_kategori` WHERE `nama` = 'Finish 3rd' LIMIT 1)),
(36, (SELECT `id_sub_kategori` FROM `sub_kategori` WHERE `nama` = 'Finish Gloss 3rd' LIMIT 1)),
(37, (SELECT `id_sub_kategori` FROM `sub_kategori` WHERE `nama` = 'Primer 1st' LIMIT 1)),
(38, (SELECT `id_sub_kategori` FROM `sub_kategori` WHERE `nama` = 'Finish Gloss 3rd' LIMIT 1)),
(39, (SELECT `id_sub_kategori` FROM `sub_kategori` WHERE `nama` = 'Finish Matte 3rd' LIMIT 1)),
(40, (SELECT `id_sub_kategori` FROM `sub_kategori` WHERE `nama` = 'Primer 1st' LIMIT 1)),
(40, (SELECT `id_sub_kategori` FROM `sub_kategori` WHERE `nama` = 'Primer 2nd' LIMIT 1)),
(41, (SELECT `id_sub_kategori` FROM `sub_kategori` WHERE `nama` = 'Protect 1st' LIMIT 1)),
(41, (SELECT `id_sub_kategori` FROM `sub_kategori` WHERE `nama` = 'Protect 2nd' LIMIT 1)),
(42, (SELECT `id_sub_kategori` FROM `sub_kategori` WHERE `nama` = 'Protect 1st' LIMIT 1)),
(42, (SELECT `id_sub_kategori` FROM `sub_kategori` WHERE `nama` = 'Protect 2nd' LIMIT 1)),
(43, (SELECT `id_sub_kategori` FROM `sub_kategori` WHERE `nama` = 'Primer 1st' LIMIT 1)),
(43, (SELECT `id_sub_kategori` FROM `sub_kategori` WHERE `nama` = 'Primer 2nd' LIMIT 1)),
(44, (SELECT `id_sub_kategori` FROM `sub_kategori` WHERE `nama` = 'Primer 1st' LIMIT 1)),
(44, (SELECT `id_sub_kategori` FROM `sub_kategori` WHERE `nama` = 'Primer 2nd' LIMIT 1)),
(45, (SELECT `id_sub_kategori` FROM `sub_kategori` WHERE `nama` = 'Protect 1st' LIMIT 1)),
(45, (SELECT `id_sub_kategori` FROM `sub_kategori` WHERE `nama` = 'Protect 2nd' LIMIT 1)),
(46, (SELECT `id_sub_kategori` FROM `sub_kategori` WHERE `nama` = 'Primer 1st' LIMIT 1)),
(46, (SELECT `id_sub_kategori` FROM `sub_kategori` WHERE `nama` = 'Primer 2nd' LIMIT 1)),
(47, (SELECT `id_sub_kategori` FROM `sub_kategori` WHERE `nama` = 'Primer 1st' LIMIT 1)),
(47, (SELECT `id_sub_kategori` FROM `sub_kategori` WHERE `nama` = 'Primer 2nd' LIMIT 1)),
(48, (SELECT `id_sub_kategori` FROM `sub_kategori` WHERE `nama` = 'Primer 1st' LIMIT 1)),
(48, (SELECT `id_sub_kategori` FROM `sub_kategori` WHERE `nama` = 'Primer 2nd' LIMIT 1)),
(49, (SELECT `id_sub_kategori` FROM `sub_kategori` WHERE `nama` = 'Primer 1st' LIMIT 1)),
(49, (SELECT `id_sub_kategori` FROM `sub_kategori` WHERE `nama` = 'Primer 2nd' LIMIT 1)),
(50, (SELECT `id_sub_kategori` FROM `sub_kategori` WHERE `nama` = 'Mortar' LIMIT 1)),
(51, (SELECT `id_sub_kategori` FROM `sub_kategori` WHERE `nama` = 'Mortar' LIMIT 1)),
(51, (SELECT `id_sub_kategori` FROM `sub_kategori` WHERE `nama` = 'Primer 1st' LIMIT 1)),
(52, (SELECT `id_sub_kategori` FROM `sub_kategori` WHERE `nama` = 'Primer 1st' LIMIT 1)),
(53, (SELECT `id_sub_kategori` FROM `sub_kategori` WHERE `nama` = 'Primer 1st' LIMIT 1)),
(54, (SELECT `id_sub_kategori` FROM `sub_kategori` WHERE `nama` = 'Primer 1st' LIMIT 1)),
(54, (SELECT `id_sub_kategori` FROM `sub_kategori` WHERE `nama` = 'Primer 2nd' LIMIT 1)),
(55, (SELECT `id_sub_kategori` FROM `sub_kategori` WHERE `nama` = 'Mortar' LIMIT 1)),
(56, (SELECT `id_sub_kategori` FROM `sub_kategori` WHERE `nama` = 'Finish 3rd' LIMIT 1)),
(57, (SELECT `id_sub_kategori` FROM `sub_kategori` WHERE `nama` = 'Finish Gloss 3rd' LIMIT 1)),
(58, (SELECT `id_sub_kategori` FROM `sub_kategori` WHERE `nama` = 'Finish Gloss 3rd' LIMIT 1)),
(59, (SELECT `id_sub_kategori` FROM `sub_kategori` WHERE `nama` = 'Primer 1st' LIMIT 1)),
(60, (SELECT `id_sub_kategori` FROM `sub_kategori` WHERE `nama` = 'Finish Gloss 3rd' LIMIT 1)),
(61, (SELECT `id_sub_kategori` FROM `sub_kategori` WHERE `nama` = 'Finish 3rd' LIMIT 1)),
(62, (SELECT `id_sub_kategori` FROM `sub_kategori` WHERE `nama` = 'Finish Matte 3rd' LIMIT 1)),
(63, (SELECT `id_sub_kategori` FROM `sub_kategori` WHERE `nama` = 'Finish 3rd' LIMIT 1)),
(64, (SELECT `id_sub_kategori` FROM `sub_kategori` WHERE `nama` = 'Primer 1st' LIMIT 1)),
(64, (SELECT `id_sub_kategori` FROM `sub_kategori` WHERE `nama` = 'Primer 2nd' LIMIT 1)),
(65, (SELECT `id_sub_kategori` FROM `sub_kategori` WHERE `nama` = 'Mortar' LIMIT 1)),
(66, (SELECT `id_sub_kategori` FROM `sub_kategori` WHERE `nama` = 'Primer 1st' LIMIT 1)),
(66, (SELECT `id_sub_kategori` FROM `sub_kategori` WHERE `nama` = 'Primer 2nd' LIMIT 1)),
(67, (SELECT `id_sub_kategori` FROM `sub_kategori` WHERE `nama` = 'Primer 1st' LIMIT 1)),
(67, (SELECT `id_sub_kategori` FROM `sub_kategori` WHERE `nama` = 'Primer 2nd' LIMIT 1)),
(68, (SELECT `id_sub_kategori` FROM `sub_kategori` WHERE `nama` = 'Protect 3rd' LIMIT 1)),
(69, (SELECT `id_sub_kategori` FROM `sub_kategori` WHERE `nama` = 'Protect 3rd' LIMIT 1)),
(70, (SELECT `id_sub_kategori` FROM `sub_kategori` WHERE `nama` = 'Finish 3rd' LIMIT 1)),
(71, (SELECT `id_sub_kategori` FROM `sub_kategori` WHERE `nama` = 'Finish 3rd' LIMIT 1)),
(72, (SELECT `id_sub_kategori` FROM `sub_kategori` WHERE `nama` = 'Protect 3rd' LIMIT 1)),
(73, (SELECT `id_sub_kategori` FROM `sub_kategori` WHERE `nama` = 'Finish 3rd' LIMIT 1)),
(74, (SELECT `id_sub_kategori` FROM `sub_kategori` WHERE `nama` = 'Mortar' LIMIT 1)),
(75, (SELECT `id_sub_kategori` FROM `sub_kategori` WHERE `nama` = 'Protect 3rd' LIMIT 1)),
(76, (SELECT `id_sub_kategori` FROM `sub_kategori` WHERE `nama` = 'Protect 3rd' LIMIT 1)),
(77, (SELECT `id_sub_kategori` FROM `sub_kategori` WHERE `nama` = 'Finish 3rd' LIMIT 1)),
(78, (SELECT `id_sub_kategori` FROM `sub_kategori` WHERE `nama` = 'Protect 3rd' LIMIT 1));

INSERT INTO `produk_lokasi_penggunaan` (`id_produk`, `id_lokasi_penggunaan`) VALUES
(1, (SELECT `id_lokasi_penggunaan` FROM `lokasi_penggunaan` WHERE `nama` = 'Besi Indoor' LIMIT 1)),
(1, (SELECT `id_lokasi_penggunaan` FROM `lokasi_penggunaan` WHERE `nama` = 'Beton Indoor' LIMIT 1)),
(2, (SELECT `id_lokasi_penggunaan` FROM `lokasi_penggunaan` WHERE `nama` = 'Besi Outdoor' LIMIT 1)),
(2, (SELECT `id_lokasi_penggunaan` FROM `lokasi_penggunaan` WHERE `nama` = 'Beton Outdoor' LIMIT 1)),
(3, (SELECT `id_lokasi_penggunaan` FROM `lokasi_penggunaan` WHERE `nama` = 'Besi Outdoor' LIMIT 1)),
(4, (SELECT `id_lokasi_penggunaan` FROM `lokasi_penggunaan` WHERE `nama` = 'Besi Outdoor' LIMIT 1)),
(5, (SELECT `id_lokasi_penggunaan` FROM `lokasi_penggunaan` WHERE `nama` = 'Kayu' LIMIT 1)),
(5, (SELECT `id_lokasi_penggunaan` FROM `lokasi_penggunaan` WHERE `nama` = 'Beton Indoor' LIMIT 1)),
(5, (SELECT `id_lokasi_penggunaan` FROM `lokasi_penggunaan` WHERE `nama` = 'Besi Indoor' LIMIT 1)),
(6, (SELECT `id_lokasi_penggunaan` FROM `lokasi_penggunaan` WHERE `nama` = 'Kayu' LIMIT 1)),
(6, (SELECT `id_lokasi_penggunaan` FROM `lokasi_penggunaan` WHERE `nama` = 'Beton Outdoor' LIMIT 1)),
(6, (SELECT `id_lokasi_penggunaan` FROM `lokasi_penggunaan` WHERE `nama` = 'Besi Outdoor' LIMIT 1)),
(7, (SELECT `id_lokasi_penggunaan` FROM `lokasi_penggunaan` WHERE `nama` = 'Besi Outdoor' LIMIT 1)),
(7, (SELECT `id_lokasi_penggunaan` FROM `lokasi_penggunaan` WHERE `nama` = 'Beton Outdoor' LIMIT 1)),
(8, (SELECT `id_lokasi_penggunaan` FROM `lokasi_penggunaan` WHERE `nama` = 'Besi Indoor' LIMIT 1)),
(8, (SELECT `id_lokasi_penggunaan` FROM `lokasi_penggunaan` WHERE `nama` = 'Beton Indoor' LIMIT 1)),
(9, (SELECT `id_lokasi_penggunaan` FROM `lokasi_penggunaan` WHERE `nama` = 'Besi Outdoor' LIMIT 1)),
(10, (SELECT `id_lokasi_penggunaan` FROM `lokasi_penggunaan` WHERE `nama` = 'Besi Outdoor' LIMIT 1)),
(10, (SELECT `id_lokasi_penggunaan` FROM `lokasi_penggunaan` WHERE `nama` = 'Beton Outdoor' LIMIT 1)),
(10, (SELECT `id_lokasi_penggunaan` FROM `lokasi_penggunaan` WHERE `nama` = 'Lantai Basah' LIMIT 1)),
(11, (SELECT `id_lokasi_penggunaan` FROM `lokasi_penggunaan` WHERE `nama` = 'Besi Outdoor' LIMIT 1)),
(11, (SELECT `id_lokasi_penggunaan` FROM `lokasi_penggunaan` WHERE `nama` = 'Beton Outdoor' LIMIT 1)),
(11, (SELECT `id_lokasi_penggunaan` FROM `lokasi_penggunaan` WHERE `nama` = 'Lantai Basah' LIMIT 1)),
(12, (SELECT `id_lokasi_penggunaan` FROM `lokasi_penggunaan` WHERE `nama` = 'Besi Indoor' LIMIT 1)),
(12, (SELECT `id_lokasi_penggunaan` FROM `lokasi_penggunaan` WHERE `nama` = 'Beton Indoor' LIMIT 1)),
(12, (SELECT `id_lokasi_penggunaan` FROM `lokasi_penggunaan` WHERE `nama` = 'Lantai Kering' LIMIT 1)),
(13, (SELECT `id_lokasi_penggunaan` FROM `lokasi_penggunaan` WHERE `nama` = 'Besi Outdoor' LIMIT 1)),
(14, (SELECT `id_lokasi_penggunaan` FROM `lokasi_penggunaan` WHERE `nama` = 'Besi Outdoor' LIMIT 1)),
(15, (SELECT `id_lokasi_penggunaan` FROM `lokasi_penggunaan` WHERE `nama` = 'Besi Outdoor' LIMIT 1)),
(15, (SELECT `id_lokasi_penggunaan` FROM `lokasi_penggunaan` WHERE `nama` = 'Kayu' LIMIT 1)),
(15, (SELECT `id_lokasi_penggunaan` FROM `lokasi_penggunaan` WHERE `nama` = 'Lantai Basah' LIMIT 1)),
(16, (SELECT `id_lokasi_penggunaan` FROM `lokasi_penggunaan` WHERE `nama` = 'Besi' LIMIT 1)),
(16, (SELECT `id_lokasi_penggunaan` FROM `lokasi_penggunaan` WHERE `nama` = 'Kayu' LIMIT 1)),
(16, (SELECT `id_lokasi_penggunaan` FROM `lokasi_penggunaan` WHERE `nama` = 'Lantai Basah' LIMIT 1)),
(17, (SELECT `id_lokasi_penggunaan` FROM `lokasi_penggunaan` WHERE `nama` = 'Besi Indoor' LIMIT 1)),
(18, (SELECT `id_lokasi_penggunaan` FROM `lokasi_penggunaan` WHERE `nama` = 'Besi Outdoor' LIMIT 1)),
(19, (SELECT `id_lokasi_penggunaan` FROM `lokasi_penggunaan` WHERE `nama` = 'Besi Outdoor' LIMIT 1)),
(20, (SELECT `id_lokasi_penggunaan` FROM `lokasi_penggunaan` WHERE `nama` = 'Besi Outdoor' LIMIT 1)),
(21, (SELECT `id_lokasi_penggunaan` FROM `lokasi_penggunaan` WHERE `nama` = 'Besi Outdoor' LIMIT 1)),
(22, (SELECT `id_lokasi_penggunaan` FROM `lokasi_penggunaan` WHERE `nama` = 'Besi Outdoor' LIMIT 1)),
(22, (SELECT `id_lokasi_penggunaan` FROM `lokasi_penggunaan` WHERE `nama` = 'Beton Outdoor' LIMIT 1)),
(23, (SELECT `id_lokasi_penggunaan` FROM `lokasi_penggunaan` WHERE `nama` = 'Besi Outdoor' LIMIT 1)),
(23, (SELECT `id_lokasi_penggunaan` FROM `lokasi_penggunaan` WHERE `nama` = 'Beton Outdoor' LIMIT 1)),
(24, (SELECT `id_lokasi_penggunaan` FROM `lokasi_penggunaan` WHERE `nama` = 'Besi Indoor' LIMIT 1)),
(24, (SELECT `id_lokasi_penggunaan` FROM `lokasi_penggunaan` WHERE `nama` = 'Beton Indoor' LIMIT 1)),
(25, (SELECT `id_lokasi_penggunaan` FROM `lokasi_penggunaan` WHERE `nama` = 'Besi Outdoor' LIMIT 1)),
(25, (SELECT `id_lokasi_penggunaan` FROM `lokasi_penggunaan` WHERE `nama` = 'Beton Outdoor' LIMIT 1)),
(26, (SELECT `id_lokasi_penggunaan` FROM `lokasi_penggunaan` WHERE `nama` = 'Besi Outdoor' LIMIT 1)),
(26, (SELECT `id_lokasi_penggunaan` FROM `lokasi_penggunaan` WHERE `nama` = 'Lantai Basah' LIMIT 1)),
(27, (SELECT `id_lokasi_penggunaan` FROM `lokasi_penggunaan` WHERE `nama` = 'Dalam Air' LIMIT 1)),
(28, (SELECT `id_lokasi_penggunaan` FROM `lokasi_penggunaan` WHERE `nama` = 'Dalam Air' LIMIT 1)),
(29, (SELECT `id_lokasi_penggunaan` FROM `lokasi_penggunaan` WHERE `nama` = 'Beton Indoor' LIMIT 1)),
(30, (SELECT `id_lokasi_penggunaan` FROM `lokasi_penggunaan` WHERE `nama` = 'Besi Outdoor' LIMIT 1)),
(30, (SELECT `id_lokasi_penggunaan` FROM `lokasi_penggunaan` WHERE `nama` = 'Beton Outdoor' LIMIT 1)),
(31, (SELECT `id_lokasi_penggunaan` FROM `lokasi_penggunaan` WHERE `nama` = 'Besi Outdoor' LIMIT 1)),
(31, (SELECT `id_lokasi_penggunaan` FROM `lokasi_penggunaan` WHERE `nama` = 'Beton Outdoor' LIMIT 1)),
(32, (SELECT `id_lokasi_penggunaan` FROM `lokasi_penggunaan` WHERE `nama` = 'Besi Outdoor' LIMIT 1)),
(32, (SELECT `id_lokasi_penggunaan` FROM `lokasi_penggunaan` WHERE `nama` = 'Beton Outdoor' LIMIT 1)),
(33, (SELECT `id_lokasi_penggunaan` FROM `lokasi_penggunaan` WHERE `nama` = 'Besi Outdoor' LIMIT 1)),
(33, (SELECT `id_lokasi_penggunaan` FROM `lokasi_penggunaan` WHERE `nama` = 'Beton Outdoor' LIMIT 1)),
(34, (SELECT `id_lokasi_penggunaan` FROM `lokasi_penggunaan` WHERE `nama` = 'Beton Outdoor' LIMIT 1)),
(34, (SELECT `id_lokasi_penggunaan` FROM `lokasi_penggunaan` WHERE `nama` = 'Besi Outdoor' LIMIT 1)),
(35, (SELECT `id_lokasi_penggunaan` FROM `lokasi_penggunaan` WHERE `nama` = 'Besi Outdoor' LIMIT 1)),
(35, (SELECT `id_lokasi_penggunaan` FROM `lokasi_penggunaan` WHERE `nama` = 'Beton Outdoor' LIMIT 1)),
(36, (SELECT `id_lokasi_penggunaan` FROM `lokasi_penggunaan` WHERE `nama` = 'Besi Outdoor' LIMIT 1)),
(36, (SELECT `id_lokasi_penggunaan` FROM `lokasi_penggunaan` WHERE `nama` = 'Beton Outdoor' LIMIT 1)),
(37, (SELECT `id_lokasi_penggunaan` FROM `lokasi_penggunaan` WHERE `nama` = 'Besi Outdoor' LIMIT 1)),
(37, (SELECT `id_lokasi_penggunaan` FROM `lokasi_penggunaan` WHERE `nama` = 'Beton Outdoor' LIMIT 1)),
(38, (SELECT `id_lokasi_penggunaan` FROM `lokasi_penggunaan` WHERE `nama` = 'Besi Outdoor' LIMIT 1)),
(38, (SELECT `id_lokasi_penggunaan` FROM `lokasi_penggunaan` WHERE `nama` = 'Beton Outdoor' LIMIT 1)),
(39, (SELECT `id_lokasi_penggunaan` FROM `lokasi_penggunaan` WHERE `nama` = 'Besi Outdoor' LIMIT 1)),
(39, (SELECT `id_lokasi_penggunaan` FROM `lokasi_penggunaan` WHERE `nama` = 'Beton Outdoor' LIMIT 1)),
(40, (SELECT `id_lokasi_penggunaan` FROM `lokasi_penggunaan` WHERE `nama` = 'Besi Outdoor' LIMIT 1)),
(40, (SELECT `id_lokasi_penggunaan` FROM `lokasi_penggunaan` WHERE `nama` = 'Beton Outdoor' LIMIT 1)),
(41, (SELECT `id_lokasi_penggunaan` FROM `lokasi_penggunaan` WHERE `nama` = 'Besi Outdoor' LIMIT 1)),
(41, (SELECT `id_lokasi_penggunaan` FROM `lokasi_penggunaan` WHERE `nama` = 'Beton Outdoor' LIMIT 1)),
(42, (SELECT `id_lokasi_penggunaan` FROM `lokasi_penggunaan` WHERE `nama` = 'Besi Outdoor' LIMIT 1)),
(42, (SELECT `id_lokasi_penggunaan` FROM `lokasi_penggunaan` WHERE `nama` = 'Beton Outdoor' LIMIT 1)),
(43, (SELECT `id_lokasi_penggunaan` FROM `lokasi_penggunaan` WHERE `nama` = 'Besi Outdoor' LIMIT 1)),
(43, (SELECT `id_lokasi_penggunaan` FROM `lokasi_penggunaan` WHERE `nama` = 'Beton Outdoor' LIMIT 1)),
(44, (SELECT `id_lokasi_penggunaan` FROM `lokasi_penggunaan` WHERE `nama` = 'Besi Outdoor' LIMIT 1)),
(44, (SELECT `id_lokasi_penggunaan` FROM `lokasi_penggunaan` WHERE `nama` = 'Beton Outdoor' LIMIT 1)),
(45, (SELECT `id_lokasi_penggunaan` FROM `lokasi_penggunaan` WHERE `nama` = 'Besi Outdoor' LIMIT 1)),
(45, (SELECT `id_lokasi_penggunaan` FROM `lokasi_penggunaan` WHERE `nama` = 'Beton Outdoor' LIMIT 1)),
(46, (SELECT `id_lokasi_penggunaan` FROM `lokasi_penggunaan` WHERE `nama` = 'Besi Outdoor' LIMIT 1)),
(46, (SELECT `id_lokasi_penggunaan` FROM `lokasi_penggunaan` WHERE `nama` = 'Beton Outdoor' LIMIT 1)),
(47, (SELECT `id_lokasi_penggunaan` FROM `lokasi_penggunaan` WHERE `nama` = 'Beton Outdoor' LIMIT 1)),
(47, (SELECT `id_lokasi_penggunaan` FROM `lokasi_penggunaan` WHERE `nama` = 'Lantai Basah' LIMIT 1)),
(48, (SELECT `id_lokasi_penggunaan` FROM `lokasi_penggunaan` WHERE `nama` = 'Beton Indoor' LIMIT 1)),
(48, (SELECT `id_lokasi_penggunaan` FROM `lokasi_penggunaan` WHERE `nama` = 'Lantai Kering' LIMIT 1)),
(49, (SELECT `id_lokasi_penggunaan` FROM `lokasi_penggunaan` WHERE `nama` = 'Beton Outdoor' LIMIT 1)),
(49, (SELECT `id_lokasi_penggunaan` FROM `lokasi_penggunaan` WHERE `nama` = 'Lantai Basah' LIMIT 1)),
(50, (SELECT `id_lokasi_penggunaan` FROM `lokasi_penggunaan` WHERE `nama` = 'Beton Outdoor' LIMIT 1)),
(50, (SELECT `id_lokasi_penggunaan` FROM `lokasi_penggunaan` WHERE `nama` = 'Lantai Basah' LIMIT 1)),
(51, (SELECT `id_lokasi_penggunaan` FROM `lokasi_penggunaan` WHERE `nama` = 'Beton Outdoor' LIMIT 1)),
(51, (SELECT `id_lokasi_penggunaan` FROM `lokasi_penggunaan` WHERE `nama` = 'Lantai Basah' LIMIT 1)),
(52, (SELECT `id_lokasi_penggunaan` FROM `lokasi_penggunaan` WHERE `nama` = 'Beton Outdoor' LIMIT 1)),
(52, (SELECT `id_lokasi_penggunaan` FROM `lokasi_penggunaan` WHERE `nama` = 'Lantai Basah' LIMIT 1)),
(53, (SELECT `id_lokasi_penggunaan` FROM `lokasi_penggunaan` WHERE `nama` = 'Beton Outdoor' LIMIT 1)),
(53, (SELECT `id_lokasi_penggunaan` FROM `lokasi_penggunaan` WHERE `nama` = 'Lantai Basah' LIMIT 1)),
(54, (SELECT `id_lokasi_penggunaan` FROM `lokasi_penggunaan` WHERE `nama` = 'Beton Outdoor' LIMIT 1)),
(54, (SELECT `id_lokasi_penggunaan` FROM `lokasi_penggunaan` WHERE `nama` = 'Lantai Basah' LIMIT 1)),
(55, (SELECT `id_lokasi_penggunaan` FROM `lokasi_penggunaan` WHERE `nama` = 'Lantai Basah' LIMIT 1)),
(56, (SELECT `id_lokasi_penggunaan` FROM `lokasi_penggunaan` WHERE `nama` = 'Lantai Kering' LIMIT 1)),
(56, (SELECT `id_lokasi_penggunaan` FROM `lokasi_penggunaan` WHERE `nama` = 'Beton Indoor' LIMIT 1)),
(57, (SELECT `id_lokasi_penggunaan` FROM `lokasi_penggunaan` WHERE `nama` = 'Lantai Kering' LIMIT 1)),
(57, (SELECT `id_lokasi_penggunaan` FROM `lokasi_penggunaan` WHERE `nama` = 'Beton Indoor' LIMIT 1)),
(58, (SELECT `id_lokasi_penggunaan` FROM `lokasi_penggunaan` WHERE `nama` = 'Beton Indoor' LIMIT 1)),
(58, (SELECT `id_lokasi_penggunaan` FROM `lokasi_penggunaan` WHERE `nama` = 'Lantai Kering' LIMIT 1)),
(59, (SELECT `id_lokasi_penggunaan` FROM `lokasi_penggunaan` WHERE `nama` = 'Beton Indoor' LIMIT 1)),
(59, (SELECT `id_lokasi_penggunaan` FROM `lokasi_penggunaan` WHERE `nama` = 'Lantai Kering' LIMIT 1)),
(60, (SELECT `id_lokasi_penggunaan` FROM `lokasi_penggunaan` WHERE `nama` = 'Beton Indoor' LIMIT 1)),
(60, (SELECT `id_lokasi_penggunaan` FROM `lokasi_penggunaan` WHERE `nama` = 'Lantai Kering' LIMIT 1)),
(61, (SELECT `id_lokasi_penggunaan` FROM `lokasi_penggunaan` WHERE `nama` = 'Beton Outdoor' LIMIT 1)),
(61, (SELECT `id_lokasi_penggunaan` FROM `lokasi_penggunaan` WHERE `nama` = 'Lantai Basah' LIMIT 1)),
(62, (SELECT `id_lokasi_penggunaan` FROM `lokasi_penggunaan` WHERE `nama` = 'Beton Indoor' LIMIT 1)),
(62, (SELECT `id_lokasi_penggunaan` FROM `lokasi_penggunaan` WHERE `nama` = 'Lantai Kering' LIMIT 1)),
(63, (SELECT `id_lokasi_penggunaan` FROM `lokasi_penggunaan` WHERE `nama` = 'Beton Basah' LIMIT 1)),
(63, (SELECT `id_lokasi_penggunaan` FROM `lokasi_penggunaan` WHERE `nama` = 'Lantai Basah' LIMIT 1)),
(64, (SELECT `id_lokasi_penggunaan` FROM `lokasi_penggunaan` WHERE `nama` = 'Room Interior' LIMIT 1)),
(65, (SELECT `id_lokasi_penggunaan` FROM `lokasi_penggunaan` WHERE `nama` = 'Room Interior' LIMIT 1)),
(66, (SELECT `id_lokasi_penggunaan` FROM `lokasi_penggunaan` WHERE `nama` = 'Room Interior' LIMIT 1)),
(67, (SELECT `id_lokasi_penggunaan` FROM `lokasi_penggunaan` WHERE `nama` = 'Room Interior' LIMIT 1)),
(67, (SELECT `id_lokasi_penggunaan` FROM `lokasi_penggunaan` WHERE `nama` = 'Room Exterior' LIMIT 1)),
(68, (SELECT `id_lokasi_penggunaan` FROM `lokasi_penggunaan` WHERE `nama` = 'Room Exterior' LIMIT 1)),
(69, (SELECT `id_lokasi_penggunaan` FROM `lokasi_penggunaan` WHERE `nama` = 'Room Exterior' LIMIT 1)),
(70, (SELECT `id_lokasi_penggunaan` FROM `lokasi_penggunaan` WHERE `nama` = 'Room Exterior' LIMIT 1)),
(71, (SELECT `id_lokasi_penggunaan` FROM `lokasi_penggunaan` WHERE `nama` = 'Beton Outdoor' LIMIT 1)),
(72, (SELECT `id_lokasi_penggunaan` FROM `lokasi_penggunaan` WHERE `nama` = 'Beton Outdoor' LIMIT 1)),
(73, (SELECT `id_lokasi_penggunaan` FROM `lokasi_penggunaan` WHERE `nama` = 'Beton Outdoor' LIMIT 1)),
(74, (SELECT `id_lokasi_penggunaan` FROM `lokasi_penggunaan` WHERE `nama` = 'Beton Outdoor' LIMIT 1)),
(75, (SELECT `id_lokasi_penggunaan` FROM `lokasi_penggunaan` WHERE `nama` = 'Beton Outdoor' LIMIT 1)),
(76, (SELECT `id_lokasi_penggunaan` FROM `lokasi_penggunaan` WHERE `nama` = 'Beton Outdoor' LIMIT 1)),
(77, (SELECT `id_lokasi_penggunaan` FROM `lokasi_penggunaan` WHERE `nama` = 'Dalam Air' LIMIT 1)),
(78, (SELECT `id_lokasi_penggunaan` FROM `lokasi_penggunaan` WHERE `nama` = 'Dalam Air' LIMIT 1));

INSERT INTO `produk_kebutuhan` (`id_produk`, `id_kebutuhan`) VALUES
(1, (SELECT `id_kebutuhan` FROM `kebutuhan` WHERE `nama` = 'Cepat Kering' LIMIT 1)),
(2, (SELECT `id_kebutuhan` FROM `kebutuhan` WHERE `nama` = 'Cepat Kering' LIMIT 1)),
(3, (SELECT `id_kebutuhan` FROM `kebutuhan` WHERE `nama` = 'Tahan Kimia' LIMIT 1)),
(3, (SELECT `id_kebutuhan` FROM `kebutuhan` WHERE `nama` = 'Tahan Gesekan' LIMIT 1)),
(4, (SELECT `id_kebutuhan` FROM `kebutuhan` WHERE `nama` = 'Tahan Kimia' LIMIT 1)),
(4, (SELECT `id_kebutuhan` FROM `kebutuhan` WHERE `nama` = 'Tahan Gesekan' LIMIT 1)),
(5, (SELECT `id_kebutuhan` FROM `kebutuhan` WHERE `nama` = 'Bersinar Saat Gelap' LIMIT 1)),
(6, (SELECT `id_kebutuhan` FROM `kebutuhan` WHERE `nama` = 'Tahan Panas' LIMIT 1)),
(7, (SELECT `id_kebutuhan` FROM `kebutuhan` WHERE `nama` = 'Anti Karat' LIMIT 1)),
(8, (SELECT `id_kebutuhan` FROM `kebutuhan` WHERE `nama` = 'Cepat Kering' LIMIT 1)),
(9, (SELECT `id_kebutuhan` FROM `kebutuhan` WHERE `nama` = 'Anti Karat' LIMIT 1)),
(10, (SELECT `id_kebutuhan` FROM `kebutuhan` WHERE `nama` = 'Cepat Kering' LIMIT 1)),
(11, (SELECT `id_kebutuhan` FROM `kebutuhan` WHERE `nama` = 'Cepat Kering' LIMIT 1)),
(12, (SELECT `id_kebutuhan` FROM `kebutuhan` WHERE `nama` = 'Cepat Kering' LIMIT 1)),
(13, (SELECT `id_kebutuhan` FROM `kebutuhan` WHERE `nama` = 'Anti Karat' LIMIT 1)),
(14, (SELECT `id_kebutuhan` FROM `kebutuhan` WHERE `nama` = 'Anti Karat' LIMIT 1)),
(15, (SELECT `id_kebutuhan` FROM `kebutuhan` WHERE `nama` = 'Cepat Kering' LIMIT 1)),
(16, (SELECT `id_kebutuhan` FROM `kebutuhan` WHERE `nama` = 'Tahan Kimia' LIMIT 1)),
(16, (SELECT `id_kebutuhan` FROM `kebutuhan` WHERE `nama` = 'Tahan Gesekan' LIMIT 1)),
(17, (SELECT `id_kebutuhan` FROM `kebutuhan` WHERE `nama` = 'Cepat Kering' LIMIT 1)),
(18, (SELECT `id_kebutuhan` FROM `kebutuhan` WHERE `nama` = 'Tahan Karat' LIMIT 1)),
(19, (SELECT `id_kebutuhan` FROM `kebutuhan` WHERE `nama` = 'Tahan Abrasi' LIMIT 1)),
(20, (SELECT `id_kebutuhan` FROM `kebutuhan` WHERE `nama` = 'Tahan Kimia' LIMIT 1)),
(20, (SELECT `id_kebutuhan` FROM `kebutuhan` WHERE `nama` = 'Tahan Bahan Bakar' LIMIT 1)),
(21, (SELECT `id_kebutuhan` FROM `kebutuhan` WHERE `nama` = 'Tahan Kimia' LIMIT 1)),
(21, (SELECT `id_kebutuhan` FROM `kebutuhan` WHERE `nama` = 'Tahan Bahan Bakar' LIMIT 1)),
(21, (SELECT `id_kebutuhan` FROM `kebutuhan` WHERE `nama` = 'Tahan Gesekan' LIMIT 1)),
(22, (SELECT `id_kebutuhan` FROM `kebutuhan` WHERE `nama` = 'Tahan Kimia' LIMIT 1)),
(22, (SELECT `id_kebutuhan` FROM `kebutuhan` WHERE `nama` = 'Cepat Kering' LIMIT 1)),
(23, (SELECT `id_kebutuhan` FROM `kebutuhan` WHERE `nama` = 'Tahan Kimia' LIMIT 1)),
(23, (SELECT `id_kebutuhan` FROM `kebutuhan` WHERE `nama` = 'Tahan Bahan Bakar' LIMIT 1)),
(23, (SELECT `id_kebutuhan` FROM `kebutuhan` WHERE `nama` = 'Tahan Gesekan' LIMIT 1)),
(24, (SELECT `id_kebutuhan` FROM `kebutuhan` WHERE `nama` = 'Tahan Kimia' LIMIT 1)),
(24, (SELECT `id_kebutuhan` FROM `kebutuhan` WHERE `nama` = 'Tahan Gesekan' LIMIT 1)),
(25, (SELECT `id_kebutuhan` FROM `kebutuhan` WHERE `nama` = 'Cepat Kering' LIMIT 1)),
(25, (SELECT `id_kebutuhan` FROM `kebutuhan` WHERE `nama` = 'Tahan Kimia' LIMIT 1)),
(26, (SELECT `id_kebutuhan` FROM `kebutuhan` WHERE `nama` = 'Tahan Kimia' LIMIT 1)),
(27, (SELECT `id_kebutuhan` FROM `kebutuhan` WHERE `nama` = 'Tahan Kimia' LIMIT 1)),
(28, (SELECT `id_kebutuhan` FROM `kebutuhan` WHERE `nama` = 'Tahan Gesekan' LIMIT 1)),
(28, (SELECT `id_kebutuhan` FROM `kebutuhan` WHERE `nama` = 'Tahan Kimia' LIMIT 1)),
(29, (SELECT `id_kebutuhan` FROM `kebutuhan` WHERE `nama` = 'Tahan Gesekan' LIMIT 1)),
(29, (SELECT `id_kebutuhan` FROM `kebutuhan` WHERE `nama` = 'Tahan Kimia' LIMIT 1)),
(30, (SELECT `id_kebutuhan` FROM `kebutuhan` WHERE `nama` = 'Marka' LIMIT 1)),
(31, (SELECT `id_kebutuhan` FROM `kebutuhan` WHERE `nama` = 'Marka' LIMIT 1)),
(32, (SELECT `id_kebutuhan` FROM `kebutuhan` WHERE `nama` = 'Marka' LIMIT 1)),
(33, (SELECT `id_kebutuhan` FROM `kebutuhan` WHERE `nama` = 'Tahan Gesekan' LIMIT 1)),
(34, (SELECT `id_kebutuhan` FROM `kebutuhan` WHERE `nama` = 'Tahan Sinar Matahari' LIMIT 1)),
(35, (SELECT `id_kebutuhan` FROM `kebutuhan` WHERE `nama` = 'Tahan Sinar Matahari' LIMIT 1)),
(35, (SELECT `id_kebutuhan` FROM `kebutuhan` WHERE `nama` = 'Cepat Kering' LIMIT 1)),
(36, (SELECT `id_kebutuhan` FROM `kebutuhan` WHERE `nama` = 'Cepat Kering' LIMIT 1)),
(37, (SELECT `id_kebutuhan` FROM `kebutuhan` WHERE `nama` = 'Cepat Kering' LIMIT 1)),
(37, (SELECT `id_kebutuhan` FROM `kebutuhan` WHERE `nama` = 'Tahan Sinar Matahari' LIMIT 1)),
(38, (SELECT `id_kebutuhan` FROM `kebutuhan` WHERE `nama` = 'Tahan Karat' LIMIT 1)),
(38, (SELECT `id_kebutuhan` FROM `kebutuhan` WHERE `nama` = 'Tahan Abrasi' LIMIT 1)),
(39, (SELECT `id_kebutuhan` FROM `kebutuhan` WHERE `nama` = 'Tahan Karat' LIMIT 1)),
(39, (SELECT `id_kebutuhan` FROM `kebutuhan` WHERE `nama` = 'Tahan Abrasi' LIMIT 1)),
(40, (SELECT `id_kebutuhan` FROM `kebutuhan` WHERE `nama` = 'Tahan Karat' LIMIT 1)),
(40, (SELECT `id_kebutuhan` FROM `kebutuhan` WHERE `nama` = 'Tahan Abrasi' LIMIT 1)),
(41, (SELECT `id_kebutuhan` FROM `kebutuhan` WHERE `nama` = 'Tahan Abrasi' LIMIT 1)),
(41, (SELECT `id_kebutuhan` FROM `kebutuhan` WHERE `nama` = 'Anti Karat' LIMIT 1)),
(42, (SELECT `id_kebutuhan` FROM `kebutuhan` WHERE `nama` = 'Tahan Panas' LIMIT 1)),
(42, (SELECT `id_kebutuhan` FROM `kebutuhan` WHERE `nama` = 'Anti Karat' LIMIT 1)),
(42, (SELECT `id_kebutuhan` FROM `kebutuhan` WHERE `nama` = 'Tahan Abrasi' LIMIT 1)),
(43, (SELECT `id_kebutuhan` FROM `kebutuhan` WHERE `nama` = 'Cepat Kering' LIMIT 1)),
(44, (SELECT `id_kebutuhan` FROM `kebutuhan` WHERE `nama` = 'Tahan Panas' LIMIT 1)),
(44, (SELECT `id_kebutuhan` FROM `kebutuhan` WHERE `nama` = 'Tahan Sinar Matahari' LIMIT 1)),
(45, (SELECT `id_kebutuhan` FROM `kebutuhan` WHERE `nama` = 'Tahan Panas' LIMIT 1)),
(45, (SELECT `id_kebutuhan` FROM `kebutuhan` WHERE `nama` = 'Tahan Sinar Matahari' LIMIT 1)),
(46, (SELECT `id_kebutuhan` FROM `kebutuhan` WHERE `nama` = 'Tahan Panas' LIMIT 1)),
(47, (SELECT `id_kebutuhan` FROM `kebutuhan` WHERE `nama` = 'Tahan Abrasi' LIMIT 1)),
(47, (SELECT `id_kebutuhan` FROM `kebutuhan` WHERE `nama` = 'Tahan Benturan' LIMIT 1)),
(48, (SELECT `id_kebutuhan` FROM `kebutuhan` WHERE `nama` = 'Tidak Bau Tajam' LIMIT 1)),
(49, (SELECT `id_kebutuhan` FROM `kebutuhan` WHERE `nama` = 'Anti Static' LIMIT 1)),
(50, (SELECT `id_kebutuhan` FROM `kebutuhan` WHERE `nama` = 'Tidak Bau Tajam' LIMIT 1)),
(51, (SELECT `id_kebutuhan` FROM `kebutuhan` WHERE `nama` = 'Viskositas Rendah' LIMIT 1)),
(52, (SELECT `id_kebutuhan` FROM `kebutuhan` WHERE `nama` = 'Oily Surfaces' LIMIT 1)),
(53, (SELECT `id_kebutuhan` FROM `kebutuhan` WHERE `nama` = 'Tahan Abrasi' LIMIT 1)),
(53, (SELECT `id_kebutuhan` FROM `kebutuhan` WHERE `nama` = 'Tahan Gesekan' LIMIT 1)),
(54, (SELECT `id_kebutuhan` FROM `kebutuhan` WHERE `nama` = 'Cepat Kering' LIMIT 1)),
(55, (SELECT `id_kebutuhan` FROM `kebutuhan` WHERE `nama` = 'Tahan Gesekan' LIMIT 1)),
(56, (SELECT `id_kebutuhan` FROM `kebutuhan` WHERE `nama` = 'Tahan Gesekan' LIMIT 1)),
(56, (SELECT `id_kebutuhan` FROM `kebutuhan` WHERE `nama` = 'Tahan Kimia' LIMIT 1)),
(57, (SELECT `id_kebutuhan` FROM `kebutuhan` WHERE `nama` = 'Tahan Kimia' LIMIT 1)),
(58, (SELECT `id_kebutuhan` FROM `kebutuhan` WHERE `nama` = 'Tahan Gesekan' LIMIT 1)),
(58, (SELECT `id_kebutuhan` FROM `kebutuhan` WHERE `nama` = 'Tahan Kimia' LIMIT 1)),
(59, (SELECT `id_kebutuhan` FROM `kebutuhan` WHERE `nama` = 'Tahan Gesekan' LIMIT 1)),
(60, (SELECT `id_kebutuhan` FROM `kebutuhan` WHERE `nama` = 'Anti Static' LIMIT 1)),
(60, (SELECT `id_kebutuhan` FROM `kebutuhan` WHERE `nama` = 'Cepat Kering' LIMIT 1)),
(60, (SELECT `id_kebutuhan` FROM `kebutuhan` WHERE `nama` = 'Tahan Gesekan' LIMIT 1)),
(61, (SELECT `id_kebutuhan` FROM `kebutuhan` WHERE `nama` = 'Marka' LIMIT 1)),
(62, (SELECT `id_kebutuhan` FROM `kebutuhan` WHERE `nama` = 'Tahan Gesekan' LIMIT 1)),
(63, (SELECT `id_kebutuhan` FROM `kebutuhan` WHERE `nama` = 'Marka' LIMIT 1)),
(64, (SELECT `id_kebutuhan` FROM `kebutuhan` WHERE `nama` = 'Cepat Kering' LIMIT 1)),
(65, (SELECT `id_kebutuhan` FROM `kebutuhan` WHERE `nama` = 'Cepat Kering' LIMIT 1)),
(66, (SELECT `id_kebutuhan` FROM `kebutuhan` WHERE `nama` = 'Mudah Dibersihkan' LIMIT 1)),
(67, (SELECT `id_kebutuhan` FROM `kebutuhan` WHERE `nama` = 'Mudah Dibersihkan' LIMIT 1)),
(67, (SELECT `id_kebutuhan` FROM `kebutuhan` WHERE `nama` = 'Tidak Bau Tajam' LIMIT 1)),
(68, (SELECT `id_kebutuhan` FROM `kebutuhan` WHERE `nama` = 'Tahan Cuaca' LIMIT 1)),
(69, (SELECT `id_kebutuhan` FROM `kebutuhan` WHERE `nama` = 'Elastis' LIMIT 1)),
(70, (SELECT `id_kebutuhan` FROM `kebutuhan` WHERE `nama` = 'Tahan Cuaca' LIMIT 1)),
(71, (SELECT `id_kebutuhan` FROM `kebutuhan` WHERE `nama` = 'Tahan Cuaca' LIMIT 1)),
(72, (SELECT `id_kebutuhan` FROM `kebutuhan` WHERE `nama` = 'Tahan Cuaca' LIMIT 1)),
(73, (SELECT `id_kebutuhan` FROM `kebutuhan` WHERE `nama` = 'Tidak Bau Tajam' LIMIT 1)),
(73, (SELECT `id_kebutuhan` FROM `kebutuhan` WHERE `nama` = 'Elastis' LIMIT 1)),
(74, (SELECT `id_kebutuhan` FROM `kebutuhan` WHERE `nama` = 'Tahan Gesekan' LIMIT 1)),
(75, (SELECT `id_kebutuhan` FROM `kebutuhan` WHERE `nama` = 'Elastis' LIMIT 1)),
(75, (SELECT `id_kebutuhan` FROM `kebutuhan` WHERE `nama` = 'Tahan Benturan' LIMIT 1)),
(76, (SELECT `id_kebutuhan` FROM `kebutuhan` WHERE `nama` = 'Elastis' LIMIT 1)),
(76, (SELECT `id_kebutuhan` FROM `kebutuhan` WHERE `nama` = 'Tahan Karat' LIMIT 1)),
(76, (SELECT `id_kebutuhan` FROM `kebutuhan` WHERE `nama` = 'Tahan Sinar Matahari' LIMIT 1)),
(77, (SELECT `id_kebutuhan` FROM `kebutuhan` WHERE `nama` = 'Bawah Kapal' LIMIT 1)),
(77, (SELECT `id_kebutuhan` FROM `kebutuhan` WHERE `nama` = 'Cepat Kering' LIMIT 1)),
(78, (SELECT `id_kebutuhan` FROM `kebutuhan` WHERE `nama` = 'Bawah Kapal' LIMIT 1));

SET FOREIGN_KEY_CHECKS=1;
